# -*- coding: utf-8 -*-
"""Extra per-city content: the seasonal pattern of losses, and the commercial
property character of each city.

Kept factual and general — property types, construction eras and weather
exposure. No invented project histories, customer counts or local partnerships.
"""

# slug -> (seasonal, commercial)
X = {
"dallas": ("Dallas sees the full range: hard freezes in January and February that split attic and exterior-wall supply lines, spring hail from March through May, and summer attic temperatures above 140&deg;F that fail HVAC condensate systems and water heaters. Older inner-city stock adds year-round sewer backup risk.",
 "From Design District warehouses and Deep Ellum mixed-use to Uptown mid-rise and suburban retail. Commercial losses here are frequently vertical — a failure on an upper floor affecting several tenants below."),
"fort-worth": ("Tarrant County sits under the more active side of the spring hail corridor, and Fort Worth takes wind and hail events most years. Winter freezes hit the older housing stock hardest, where supply lines run through uninsulated crawlspaces and exterior walls.",
 "A genuinely mixed commercial base — Stockyards hospitality, downtown offices, medical district facilities and light industrial to the east and south. Historic buildings add plaster, masonry and older electrical to the scope."),
"irving": ("Freeze events are the dominant winter risk given how much of the housing stock still carries original supply plumbing. Summer brings condensate overflow, and spring storms move through the SH-114 corridor regularly.",
 "Las Colinas towers, corporate campuses, hotels and a large distribution and logistics footprint near DFW Airport. Multi-tenant coordination is the norm rather than the exception."),
"plano": ("East Plano's older stock is most exposed in a hard freeze; west Plano's newer two-storey homes see more summer attic and upstairs-appliance failures. Hail passes through most springs.",
 "Legacy West and the Tollway corridor carry substantial Class A office, alongside established retail at Willow Bend and a dense restaurant and service base in the older downtown."),
"frisco": ("Almost entirely modern construction, so the winter freeze risk is lower than in older cities — but attic-run PEX still fails at fittings. The larger pattern is summer: attic HVAC condensate overflows and upstairs supply failures reaching the ground floor.",
 "Rapid commercial growth along the Tollway and Preston corridors — offices, medical, hospitality and a large retail and entertainment base. Much of it is new build, where installation defects show up early."),
"mckinney": ("Historic downtown properties carry the freeze and older-plumbing profile; the newer subdivisions east and west see the two-storey summer pattern. Collin County takes spring hail most years.",
 "Downtown McKinney's historic commercial buildings sit alongside newer corridor retail and medical. The historic stock brings pier-and-beam, plaster and masonry considerations."),
"richardson": ("The 1955-1980 housing stock is the most freeze-exposed in the area we serve, and cast iron drain failures are effectively a year-round issue rather than a seasonal one.",
 "The Telecom Corridor carries large office and data-adjacent facilities, plus established retail along Beltline and Campbell. Older commercial buildings bring their own aging-plumbing profile."),
"garland": ("Freeze damage in the older neighbourhoods and sewer backup during heavy rain are the two recurring patterns. Spring storms move through regularly.",
 "A substantial light industrial and manufacturing base alongside neighbourhood retail. Warehouse losses here often involve racked inventory and slow-releasing concrete slabs."),
"mesquite": ("Older housing stock means freeze exposure and aging drain lines. The area sees its share of spring hail and wind, and heavy rain events bring drain backup.",
 "Retail along the I-635 and US-80 corridors, distribution facilities, and a mix of small commercial and service businesses."),
"arlington": ("Sits squarely in the spring hail corridor and takes wind events most years. Winter freezes affect the large stock of 1960s-1980s housing across the city.",
 "Entertainment district venues and hospitality, alongside a large distribution and light manufacturing base and extensive neighbourhood retail. Event-driven businesses need work phased around their calendar."),
"grand-prairie": ("Hail and wind exposure through spring, freeze risk in the older neighbourhoods, and drainage-related intrusion in the lower-lying areas during heavy rain.",
 "Heavy distribution and logistics presence along the I-20 and SH-161 corridors, plus retail and entertainment venues. Warehouse square footage drives large-loss equipment requirements."),
"carrollton": ("Polybutylene supply line failures are the standout risk and they are not seasonal — they fail without warning. Freezes accelerate it, and spring hail passes through most years.",
 "Light industrial and flex space along the Beltline and I-35E corridors, alongside established neighbourhood retail and a growing restaurant base near downtown Carrollton."),
"addison": ("Mid-rise and multi-family construction means vertical water migration is the dominant pattern year-round. Freeze events affect rooftop and exterior mechanical systems.",
 "One of the densest restaurant and hospitality concentrations in the Metroplex, plus substantial office and the Addison Airport business base. Restaurant losses carry health-department requirements."),
"farmers-branch": ("Older housing stock carries freeze and aging-drain exposure. The area takes spring storms, and heavy rain can bring drain backup in the lower sections.",
 "Manufacturing, warehouse and flex space along the I-35E and Valley View corridors, alongside neighbourhood retail and a growing mixed-use core."),
"coppell": ("Newer construction reduces freeze risk relative to neighbouring cities, but two-storey layouts with attic HVAC mean summer condensate and upstairs appliance failures dominate.",
 "A very large distribution and logistics footprint near DFW Airport, plus corporate offices and neighbourhood retail. Warehouse losses involve inventory protection as much as structure."),
"lewisville": ("Lakefront wind exposure adds to the standard spring hail pattern. Housing spans several eras, so both freeze failures in older stock and summer attic issues in newer builds are common.",
 "Retail along I-35E and the Vista Ridge corridor, light industrial to the east, and a substantial multi-family base where losses affect several units at once."),
"the-colony": ("Wind exposure from Lewisville Lake, plus the newer-construction summer pattern of attic condensate and upstairs supply failures. Freeze risk is moderate given the construction era.",
 "Grandscape anchors a large retail and entertainment base, alongside neighbourhood commercial and a growing hospitality presence."),
"allen": ("Predominantly 1990s-onward construction, so summer attic and upstairs-appliance failures outnumber freeze losses. Collin County hail passes through most springs.",
 "Watters Creek and the US-75 corridor carry retail, restaurants and offices, plus event and sports venues that need work scheduled around their calendar."),
"prosper": ("New construction throughout, with the failure pattern skewed heavily toward installation defects and summer attic HVAC problems rather than aging plumbing.",
 "Commercial development is newer and concentrated along the Preston and US-380 corridors — retail, medical and office, much of it recently built."),
"celina": ("Rapid new construction means installation-defect failures are the most common cause we see, alongside summer attic condensate. Hard freezes still catch attic-run supply lines.",
 "A smaller but fast-growing commercial base along the Preston corridor and around the historic downtown square."),
"denton": ("Freeze exposure across the older housing stock near the universities and downtown, plus spring hail and wind. Heavy rain brings drain backup in the older sections.",
 "A large student rental market, downtown square retail and hospitality, and light industrial to the south and east. Rental turnovers frequently run to a lease deadline."),
"north-richland-hills": ("Tarrant County hail exposure through spring, and freeze risk across the substantial 1960s-1990s housing stock.",
 "Neighbourhood and corridor retail along Rufe Snow and Davis, plus medical facilities and a mix of small commercial and service businesses."),
"euless": ("Airport-corridor wind exposure and spring hail, with freeze risk across the older residential stock and the large multi-family base.",
 "Hotels and airport-adjacent hospitality, retail along SH-10 and SH-121, and a substantial multi-family footprint where one failure affects several units."),
"bedford": ("Spring hail and wind, plus freeze exposure through the 1970s-1990s housing stock that makes up much of the city.",
 "Corridor retail and offices along SH-121 and Bedford Road, medical facilities, and neighbourhood commercial."),
"hurst": ("Standard Mid-Cities pattern: spring hail, winter freeze risk in the older stock, and summer attic HVAC failures in the two-storey homes.",
 "North East Mall anchors a large retail base, with medical facilities and corridor commercial along Precinct Line and SH-121."),
"grapevine": ("Lake-adjacent wind exposure, spring hail, and the freeze profile of a mixed-era housing stock including a genuinely historic core.",
 "A hospitality-heavy commercial base — hotels, Grapevine Mills, Main Street retail and restaurants, and airport-adjacent facilities. Hotel losses need floor-by-floor phasing to keep rooms sellable."),
"flower-mound": ("Larger lots and two-storey homes mean the summer attic and upstairs-supply pattern dominates. Wind exposure from the lake side, and spring hail most years.",
 "Corridor retail along FM 2499 and FM 1171, medical offices, and neighbourhood commercial rather than heavy industrial."),
"southlake": ("Custom homes with high-end finishes make the summer attic and upstairs pattern expensive rather than merely inconvenient. Spring hail is a regular event.",
 "Southlake Town Square carries a dense retail, restaurant and office base, alongside professional and medical offices along SH-114."),
"las-colinas": ("Mid-rise and high-rise construction makes vertical water migration the defining pattern, year-round. Freeze events affect rooftop mechanical and exposed risers.",
 "One of the densest corporate office concentrations in the Metroplex, plus hotels, the Urban Center and substantial multi-family. Losses routinely involve multiple tenants and multiple carriers."),
}
