# -*- coding: utf-8 -*-
"""Cost drivers and realistic timelines for each service.

Deliberately no dollar figures — pricing depends on the property and the loss,
and publishing invented numbers would be worse than useless. What people
actually need before they call is (a) what moves the price and (b) how long
they will be living with it.
"""

# slug -> (intro, [(factor, explanation), ...])
COST = {
"water-damage-restoration": ("Water losses are priced on how far the water travelled and what it touched, not on the size of the leak.", [
 ("Affected square footage", "Not the size of the puddle — the measured area water reached, including under cabinets and inside wall cavities."),
 ("Water category", "Clean supply water, greywater from an appliance, or contaminated water. Category drives what can be dried and what must be removed."),
 ("Materials involved", "Carpet and pad dry cheaply. Hardwood, engineered flooring, plaster and custom cabinetry need specialty equipment and longer drying."),
 ("Days of equipment", "Air movers and dehumidifiers are priced per unit per day. A property that dries in three days costs meaningfully less than one that takes seven."),
 ("Demolition and rebuild", "Whether materials come out at all, and how much finish work is needed to put the room back."),
 ("Access", "Second-floor and attic losses take longer to reach and equipment has to be carried."),
]),
"fire-damage-restoration": ("Fire jobs are priced in two halves — cleaning what survived, and rebuilding what did not.", [
 ("Extent of structural damage", "Charred framing and compromised structure means reconstruction rather than cleaning."),
 ("Smoke spread", "Often larger than the burn area. Smoke reaches rooms the fire never entered, and that scope is scoped separately."),
 ("Water damage from suppression", "Firefighting water frequently causes as much damage as the fire, and it needs full extraction and drying."),
 ("Contents volume", "How much is packed out, cleaned and stored while the structure is rebuilt."),
 ("Residue type", "Protein and wet smoke take far more labour per square foot than dry smoke."),
 ("Code upgrades", "Older properties often cannot be rebuilt exactly as they were, which adds electrical and plumbing work."),
]),
"smoke-damage-cleanup": ("Smoke work is labour-driven — the cost is hours of cleaning, not materials.", [
 ("Affected area", "Every surface smoke reached, including closets, cabinet interiors and rooms served by the same HVAC system."),
 ("Residue type", "Dry smoke cleans fastest. Wet smoke, protein and fuel-oil residue each take substantially longer."),
 ("HVAC contamination", "Whether ducts, coil and blower need cleaning or replacement."),
 ("How long it has sat", "Residue that has been in place for weeks has etched and corroded surfaces, converting cleaning into refinishing."),
 ("Contents processing", "Ultrasonic and textile cleaning of affected belongings is priced separately from the structure."),
 ("Sealing and repainting", "Where odour has penetrated substrate, sealing before finish is an additional step."),
]),
"mold-remediation": ("Mold pricing turns on containment and the size of the removal area, not on the visible patch.", [
 ("Size of the affected area", "Small contained areas are straightforward. Larger areas require full containment and negative air."),
 ("Containment requirements", "Barriers, negative air machines and HEPA filtration scale with the work area and how occupied the property is."),
 ("Materials removed", "Drywall and insulation are inexpensive to replace. Cabinetry, tile and hardwood are not."),
 ("The moisture source", "Remediation without fixing the source is wasted money, so the plumbing or envelope repair is part of the real cost."),
 ("Accessibility", "Crawlspaces, attics and behind-cabinet growth take longer to reach and to work in."),
 ("Post-remediation verification", "Independent clearance testing, where you want documented proof the work succeeded."),
]),
"storm-damage-restoration": ("Storm work is usually an insurance job, and the cost question is really a coverage question.", [
 ("Roof damage extent", "Repairable sections versus full replacement, and whether decking underneath is affected."),
 ("Water intrusion", "How far water travelled inside once the envelope was breached."),
 ("Emergency protection", "Tarping and board-up, which is generally reimbursable under your policy."),
 ("Exterior components", "Siding, gutters, windows, fencing and outbuildings are often damaged alongside the roof."),
 ("Code upgrades", "Current code may require decking, underlayment or ventilation that the original roof did not have."),
 ("Interior finishes", "Ceilings, insulation and flooring affected by the intrusion."),
]),
"flood-cleanup": ("Flood cleanup is priced as contamination work, which is why it costs more per square foot than clean-water drying.", [
 ("Contamination category", "Flood water is Category 3 by definition, which mandates removal rather than drying of porous materials."),
 ("Volume of material removed", "Carpet, pad, insulation, drywall to a documented height, and affected cabinetry and furniture."),
 ("Disposal", "Contaminated material carries disposal costs that clean-water debris does not."),
 ("Cleaning and disinfection", "Every remaining surface is physically cleaned before antimicrobial application — that is labour, not product."),
 ("Drying after decontamination", "The structure still has to be dried to a documented standard once it is clean."),
 ("Depth and duration", "How high the water rose and how long it sat before it receded."),
]),
"burst-pipe-repair": ("Two costs run in parallel — fixing the pipe, and dealing with everything the water reached.", [
 ("Pipe location", "An accessible attic run is a quick repair. A slab leak means locating, then tunnelling, breaking through or rerouting."),
 ("Repair versus repipe", "A single failure in sound copper is a repair. Polybutylene or heavily corroded galvanised is usually a repipe conversation."),
 ("Water damage extent", "How long the line ran before it was shut off, and how many rooms and floors the water reached."),
 ("Access and restoration", "Opening walls, ceilings or slab to reach the line, then putting those surfaces back."),
 ("Time of failure", "A pipe that burst while the property was empty for a week is a far larger job than one caught in an hour."),
 ("Pressure testing afterward", "Confirming the repair holds, and checking the rest of the run for the same failure mode &mdash; on a system where one line has failed, the others are usually the same age and material."),
]),
"water-extraction": ("Extraction is usually the first line on a larger invoice rather than a standalone job.", [
 ("Volume of standing water", "How much has to be physically removed, and whether pumping is needed before vacuum extraction."),
 ("Surface types", "Carpet, hard flooring, and water trapped beneath floating floors each require different tooling."),
 ("Equipment required", "Portable units, truck-mounted extraction or submersible pumping depending on volume and access."),
 ("Water category", "Contaminated water requires dedicated equipment and disposal handling."),
 ("Access", "Distance from the affected area to a discharge point, and whether hose can be run at all."),
 ("Time since the water appeared", "Water sitting for a day has migrated into materials a fast response would have kept dry. Extraction cost barely moves; everything downstream of it does."),
]),
"structural-drying": ("Drying is billed per piece of equipment per day, so the variable that matters is how many days it takes.", [
 ("Equipment count", "Calculated from affected volume, material types and the class of the loss — not guessed."),
 ("Days to dry standard", "Determined by daily moisture readings, not by a fixed schedule."),
 ("Dehumidifier type", "Standard refrigerant, low-grain refrigerant, or desiccant for difficult materials and larger volumes."),
 ("Specialty drying", "Wall cavity injection and hardwood floor mats add cost but frequently save materials worth far more."),
 ("Monitoring visits", "Daily readings and documentation, which is what produces the evidence your carrier needs."),
 ("Containment", "Barriers and negative air where the drying chamber has to be separated from occupied parts of the property, which is standard on any job where people are still living there."),
]),
"emergency-cleanup": ("Emergency response is priced on what the first hours actually require.", [
 ("Time of call", "Overnight, weekend and holiday response carries different rates than scheduled work."),
 ("Scope of hazard", "Electrical, structural or contamination hazards require more people and more protective equipment."),
 ("Volume of debris", "How much non-salvageable material has to be removed and disposed of."),
 ("Emergency protection", "Board-up, tarping and shoring needed to stop the damage getting worse."),
 ("Crew size", "How many technicians the situation needs in the first shift."),
 ("Depth of documentation", "Photographic records, inventories of discarded items and moisture mapping. It adds time on site and it is what your claim is later built from."),
]),
"emergency-board-up": ("This is one of the cheaper things you will do after a loss, and one of the most reliably reimbursable.", [
 ("Number and size of openings", "Standard windows and doors versus storefront glass or a blown-out garage opening."),
 ("Roof tarping area", "Square footage covered, roof pitch and how much battening is required to hold it."),
 ("Structural shoring", "Whether temporary support is needed before anyone can safely work."),
 ("Materials", "Plywood and fasteners, or polycarbonate where the property is still trading."),
 ("Fencing", "Temporary site fencing where a property will stand open for an extended period."),
 ("How long it stays up", "Temporary protection that has to survive several weeks and a second storm needs heavier fastening and periodic checking than a two-day cover."),
]),
"biohazard-cleanup": ("Biohazard pricing reflects regulated disposal, single-use protective equipment and slower, protocol-driven labour.", [
 ("Affected area and saturation", "How far fluids travelled, including below flooring and into subfloor and joist bays."),
 ("Materials removed", "Porous materials cannot be disinfected and are removed as regulated waste."),
 ("Regulated waste volume", "Disposal is charged per container through a licensed transporter, with a manifest."),
 ("Protective equipment", "Full PPE is single-use and disposed of with the waste stream."),
 ("Odour treatment", "Sealing and air treatment where decomposition has occurred."),
 ("Verification", "Cleaning verified by inspection and, where appropriate, ATP surface testing."),
]),
"odor-removal": ("Odour is priced on source removal, not on air treatment — the machines are the cheap part.", [
 ("Source type", "Protein, smoke, pet urine and tobacco each require a different chemistry and a different amount of labour."),
 ("How deeply it penetrated", "Surface residue cleans. Odour in subfloor, framing or wall cavities requires removal or sealing."),
 ("Materials removed", "Carpet, pad, insulation and affected drywall where the odour source is inside them."),
 ("HVAC involvement", "Duct, coil and blower cleaning, and flex duct replacement where the interior is contaminated."),
 ("Sealing", "Shellac-based sealing of substrates that stay in the building."),
 ("Air treatment duration", "Hydroxyl runs longer but allows occupancy; ozone is faster but requires the space to be empty."),
]),
"contents-cleaning": ("Contents are priced per item and per process, which is why the inventory matters so much.", [
 ("Item count and type", "Hard goods, soft goods, electronics and documents each run through different processes."),
 ("Cleaning method", "Ultrasonic, specialist textile washing, hand cleaning or vacuum freeze-drying."),
 ("Pack-out and storage", "Transport, climate-controlled storage volume and duration, then pack-back."),
 ("Degree of contamination", "Light smoke exposure versus Category 3 water changes both method and success rate."),
 ("Specialty items", "Artwork, instruments and heirlooms often require a conservator rather than a general process."),
 ("Documenting what cannot be saved", "Items assessed as unrecoverable are still photographed, described and inventoried before disposal, because that record is what your contents claim settles against."),
]),
"junk-removal": ("Priced on the volume your material occupies in the truck, with adjustments for weight and effort.", [
 ("Volume", "Quoted as a fraction of a full truckload once we have seen the material."),
 ("Weight-limited material", "Concrete, dirt, roofing tear-off and tile are limited by truck rating rather than space."),
 ("Labour and access", "Second floor, attic, tight stairs or a long carry to the truck."),
 ("Disassembly", "Items that will not fit through a doorway intact."),
 ("Disposal stream", "Appliances with refrigerant, electronics and mattresses carry specific handling fees."),
 ("Scheduling", "Same-day, weekend or deadline-driven work &mdash; a lease date, a listing, an HOA compliance notice &mdash; is priced differently from a scheduled weekday collection."),
]),
"storage-and-moving": ("Two components: the work of moving, and the space and time of storing.", [
 ("Volume of contents", "How much is packed, transported and stored."),
 ("Packing materials", "Cartons, wrap and custom crating for fragile or high-value items."),
 ("Storage duration", "Priced by volume and time, and normally reimbursable for the period of a covered restoration."),
 ("Climate control", "Standard for restoration storage, and not optional in a North Texas summer."),
 ("Access and stairs", "Ground floor with a close park is quicker than a third-floor walk-up."),
 ("Inventory detail", "Item-level documentation, which is what your contents claim settles against."),
]),
"renovation": ("Reconstruction cost is driven by finish level and scope, and by how much of it your policy covers.", [
 ("Scope and square footage", "How many rooms, and whether structural, electrical or plumbing work is involved."),
 ("Finish level", "Builder-grade replacement versus custom cabinetry, tile and millwork."),
 ("Code upgrades", "Work current code requires that the original construction did not include."),
 ("Permits and inspections", "Required for structural, electrical, plumbing and mechanical work, and priced into the job."),
 ("Material lead times", "Not a cost in itself, but long-lead cabinetry and flooring drive the schedule."),
 ("Matching existing finishes", "Where a seamless match needs the scope extended to a natural break line."),
]),
"residential-restoration": ("A whole-home job is the sum of its phases, and the phases are priced separately.", [
 ("Mitigation scope", "Extraction, drying, removal and cleaning in the first days."),
 ("Contents handling", "Whether belongings stay in place, get moved within the property, or are packed out."),
 ("Occupancy", "Working around a household requires containment and phasing, which takes longer than an empty property."),
 ("Reconstruction scope", "How much has to be rebuilt, and to what finish level."),
 ("Claim coverage", "What your policy pays versus what falls to you, including your deductible."),
 ("Phasing around the household", "Sequencing so a bathroom and kitchen stay usable adds days to the schedule, and on a long job time is the main cost driver."),
]),
"commercial-restoration": ("Commercial pricing weighs the cost of the work against the cost of the business being closed.", [
 ("Square footage and ceiling height", "Volume, not floor area, determines the equipment load."),
 ("Speed requirement", "Running more equipment and working overnight costs more and usually costs less than staying closed."),
 ("Equipment class", "Desiccant dehumidification, trailer units and generator power for large or cold spaces."),
 ("Phasing and containment", "Keeping part of the operation trading while work proceeds around it."),
 ("Specialty environments", "Restaurants, medical and data spaces carry compliance requirements that shape the method."),
 ("Multi-tenant coordination", "Separate scoping per unit where several carriers and leases are involved."),
]),
}

# slug -> [(phase, duration, detail), ...]
TIMELINE = {
"water-damage-restoration": [("Emergency response","First hours","Source stopped, extraction begins, moisture mapped and documented."),
 ("Drying","3-7 days typical","Equipment runs continuously with daily readings until materials hit the dry standard."),
 ("Repairs","1-3 weeks","Replacing what came out, once readings confirm the structure is dry."),
 ("Rebuild","Varies","Flooring, cabinetry and finish work, driven mostly by material lead times.")],
"fire-damage-restoration": [("Securing the property","Day one","Board-up, tarping and utilities confirmed off."),
 ("Assessment and pack-out","First week","Scope documented, contents inventoried and removed for cleaning."),
 ("Cleaning and deodorising","2-4 weeks","Structural cleaning, HVAC remediation, sealing."),
 ("Reconstruction","1-4 months","Depends heavily on structural extent and permit timelines.")],
"smoke-damage-cleanup": [("Assessment","Day one","Residue types identified and affected areas mapped, including HVAC."),
 ("Structural cleaning","3 days - 2 weeks","Method matched to residue type, room by room."),
 ("HVAC and sealing","Within the same window","Ducts, coil and blower addressed; substrates sealed."),
 ("Contents processing","2-6 weeks","Runs in parallel and usually finishes after the structure.")],
"mold-remediation": [("Inspection","Day one","Extent mapped, moisture source identified, containment planned."),
 ("Containment and removal","1-5 days","Barriers and negative air established, affected materials removed."),
 ("Cleaning and drying","2-4 days","HEPA cleaning, antimicrobial application, structure dried."),
 ("Verification and rebuild","After clearance","Independent testing where wanted, then materials replaced.")],
"storm-damage-restoration": [("Emergency protection","Same day","Tarping and board-up to stop further intrusion."),
 ("Documentation","First days","Damage recorded for the claim before any permanent work."),
 ("Adjuster and approval","1-4 weeks","Timing depends on carrier volume after a major event."),
 ("Repairs","2 weeks - 2 months","Roofing, exterior and interior finishes, subject to material availability.")],
"flood-cleanup": [("Water removal","First hours","Pumping and extraction with dedicated equipment."),
 ("Removal and disposal","1-3 days","Contaminated porous materials out and bagged."),
 ("Cleaning and disinfection","1-2 days","Physical cleaning, then EPA-registered antimicrobial."),
 ("Drying and rebuild","3-7 days, then repairs","Structure dried to standard before anything is closed up.")],
"burst-pipe-repair": [("Shut-off and extraction","First hours","Water stopped, standing water removed."),
 ("Locate and repair","Same day to 3 days","Straightforward for accessible runs; longer for slab leaks."),
 ("Drying","3-7 days","Affected structure dried and monitored daily."),
 ("Repairs","1-3 weeks","Walls, ceilings and flooring restored.")],
"water-extraction": [("Arrival and assessment","First hour","Category determined, equipment selected, area documented."),
 ("Bulk removal","1-4 hours","Pumping where depth requires it, then vacuum extraction."),
 ("Detail extraction","Same visit","Weighted extraction on carpet, specialty tools on hard floors."),
 ("Handover to drying","Same day","Air movers and dehumidifiers set before the crew leaves.")],
"structural-drying": [("Set-up","Day one","Equipment sized to the loss and positioned; baseline readings logged."),
 ("Daily monitoring","Days 2 onward","Readings at fixed points, equipment adjusted as materials release moisture."),
 ("Dry standard reached","Typically day 3-7","Materials match unaffected readings; verified, not assumed."),
 ("Equipment removal","Same day as verification","Documentation package closed out and rebuild can begin.")],
"emergency-cleanup": [("Response","Immediately","Property made safe, hazards identified, source stopped."),
 ("Documentation","First visit","Photographs before anything moves."),
 ("Debris and material removal","1-3 days","Non-salvageable material out, inventoried first."),
 ("Handover","Same week","Into drying, remediation or rebuild as the situation requires.")],
"emergency-board-up": [("Dispatch","Immediately","Treated as an active emergency regardless of hour."),
 ("Securing openings","2-6 hours","Doors, windows and large openings boarded to structure."),
 ("Roof tarping","Same visit","Battened and lapped to shed water properly."),
 ("Permanent repair","Weeks","Temporary protection is a bridge, not a solution.")],
"biohazard-cleanup": [("Assessment","On release of the scene","Cannot begin until law enforcement releases the property."),
 ("Containment and removal","1-3 days","Affected porous materials removed as regulated waste."),
 ("Cleaning and disinfection","1-2 days","Surfaces cleaned, disinfected to contact time, verified."),
 ("Odour treatment and rebuild","3-10 days","Sealing and air treatment, then materials replaced.")],
"odor-removal": [("Source identification","Day one","Finding what is producing it, including the ordinary causes."),
 ("Source removal and cleaning","1-5 days","Affected materials out, all surfaces cleaned."),
 ("Sealing","1 day","Substrates that stay in the building are sealed."),
 ("Air treatment and verification","2-7 days","Then the property sits closed and warm before re-assessment.")],
"contents-cleaning": [("Inventory and pack-out","1-3 days","Every item photographed and recorded before it moves."),
 ("Processing","1-4 weeks","Ultrasonic, textile and specialist cleaning in sequence."),
 ("Storage","Duration of the rebuild","Climate-controlled, identifiable as your lot."),
 ("Pack-back","1-2 days","Returned and placed after final cleaning, inventory reconciled.")],
"junk-removal": [("Quote","On arrival","Firm price after we have seen the material, before anything is loaded."),
 ("Removal","Same visit","From wherever the material is; the space is swept before we leave."),
 ("Sorting","Same day","Donation, recycling, e-waste and refrigerant streams separated."),
 ("Disposal","Same day","Only what genuinely has no other route reaches landfill.")],
"storage-and-moving": [("Inventory and packing","1-3 days","Item-level records with photographs and condition notes."),
 ("Transport","Same day as packing","To climate-controlled storage as an identified lot."),
 ("Storage","Duration of the work","Retrieval of specific items available while stored."),
 ("Pack-back","1-2 days","Furniture reassembled and placed, inventory reconciled item by item.")],
"renovation": [("Scope and estimate","1 week","Measured scope, written estimate, carrier submission where applicable."),
 ("Permits","1-3 weeks","Varies by jurisdiction and work type."),
 ("Rough trades","1-2 weeks","Framing, electrical, plumbing and mechanical, then inspection."),
 ("Finish and completion","2-6 weeks","Drywall through paint, flooring, cabinetry, fixtures, final inspection.")],
"residential-restoration": [("Emergency and mitigation","First week","Response, extraction, drying and removal."),
 ("Contents","Runs in parallel","Packed out, cleaned and stored, or protected in place."),
 ("Reconstruction","2 weeks - 3 months","Sequenced to keep the property livable where possible."),
 ("Completion","Final week","Final clean, walkthrough, closing documentation package.")],
"commercial-restoration": [("Emergency response","Immediately","Often overnight, to protect the next trading day."),
 ("Stabilisation","24-72 hours","Extraction and drying at scale, with containment around occupied areas."),
 ("Phased restoration","1-6 weeks","Highest-revenue areas returned to service first."),
 ("Reconstruction","Varies","Scheduled around trading hours wherever the work allows.")],
}
